ALTER TABLE "Withdrawal"
  ADD COLUMN IF NOT EXISTS "bank_name" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "account_number" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "payout_method" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Withdrawal"
  ALTER COLUMN "qr_image_url" DROP NOT NULL;
